// AI GENERATED TEST
// GENERATED BY GPT 5.2
//
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "heap.h"

// -------- comparator for ints --------
static int int_cmp(const void *a, const void *b) {
    int x = *(const int*)a;
    int y = *(const int*)b;
    return (x > y) - (x < y);
}

// -------- debug print --------
static void print_heap(Heap *h) {

    if (heap_size(h) == 0) {
        printf("NULL | ");
    } else {
        printf("%d | ", *(int*)heap_peek(h));
    }

    printf("data=[ ");
    for (size_t i = 0; i < heap_size(h); i++) {
        printf("%d ", *(int*)h->data->items[i]);
    }
    printf("]\n");
}

// -------- expected top from reference --------
static int ref_top(const int *arr, size_t n, int htype) {
    assert(n > 0);
    int top = arr[0];
    for (size_t i = 1; i < n; i++) {
        if (htype == 0) {
            if (arr[i] < top) top = arr[i];
        } else {
            if (arr[i] > top) top = arr[i];
        }
    }
    return top;
}

static void test_logged(int htype) {
    printf("\n===== %s-HEAP TEST =====\n", htype ? "MAX" : "MIN");

    Heap *h = heap_create(htype, sizeof(int), int_cmp);
    assert(h);

    int vals[] = { 5, 1, 7, 1, 3, -2, 9, 0 };
    size_t n = sizeof(vals) / sizeof(vals[0]);

    int ref[64];
    size_t ref_n = 0;

    // ---- pushes ----
    for (size_t i = 0; i < n; i++) {
        printf("\nPUSH %d\n", vals[i]);
        assert(heap_push(h, &vals[i]) == 0);
        ref[ref_n++] = vals[i];

        print_heap(h);

        int expected = ref_top(ref, ref_n, htype);
        assert(*(int*)heap_peek(h) == expected);
    }

    // ---- pops ----
    printf("\n--- POP SEQUENCE ---\n");
    while (heap_size(h) > 0) {
        int expected = ref_top(ref, ref_n, htype);
        int top = *(int*)heap_peek(h);

        printf("\nPOP (expect %d)\n", expected);
        assert(top == expected);

        assert(heap_pop(h) == 0);

        // remove one instance from ref
        size_t k = 0;
        for (; k < ref_n; k++) {
            if (ref[k] == expected) break;
        }
        assert(k < ref_n);
        ref[k] = ref[ref_n - 1];
        ref_n--;

        print_heap(h);
    }

    heap_destroy(h);
    printf("\n===== %s-HEAP OK =====\n", htype ? "MAX" : "MIN");
}

int test_heap() {
    test_logged(0);  // min-heap
    test_logged(1);  // max-heap
    printf("\nALL LOGGED HEAP TESTS PASSED\n");
    return 0;
}

